# Generated by Django 2.1.2 on 2018-10-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='epoch',
            field=models.FloatField(default=-1, help_text='Number of epochs (aka iterations on training data) for this checkpoint. Optional.'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='step',
            field=models.IntegerField(default=-1, help_text='MT system trainings steps of this checkpoint. Optional.'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='time',
            field=models.IntegerField(default=-1, help_text='Training time in number of seconds needed to obtain this checkpoint. Optional.'),
        ),
    ]
